// Code generated by "go generate"; DO NOT EDIT.

package config

func (c Config) GetEnv() string {
	return c.Env
}
func (c Config) GetPaths() []string {
	return c.Paths
}
func (c Config) GetID() int {
	return c.ID
}
