// Code generated by "go generate"; DO NOT EDIT.

package utils

func (c Bar) GetDrinks() []int {
	return c.Drinks
}
func (c Bar) GetNamer() Foo {
	return c.Namer
}
func (c Bar) GetHidden() bool {
	return c.hidden
}
